### ISSUE TITLE
Increase maximum audio latency setting

### ISSUE THREAD

**Issue by KinkMyBoot** [CasualPokePlayer/GSE#14]
According to my estimates, To achieve an audio latency equal to what 68ms on gambatte-speedrun feels like, GSE would need to allow setting the audio latency to 110-120 ms. Right now it is capped at 100ms.

Setting it to 128ms maximum has been suggested. Could also increase it more in case people on gambatte-speedrun had it set to something higher. It used to be capped at 999ms on gambatte-speedrun

**Comment by CasualPokePlayer** [comment]
This was already done in https://github.com/CasualPokePlayer/GSE/commit/cdfe57d3f1937ef470962fc906fca784a70451ac
